package cst.timesheet_JPA.model;

// Generated 12-Nov-2013 6:05:43 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employ generated by hbm2java
 */
@Entity
@Table(name = "EMPLOY", catalog = "Timesheet", uniqueConstraints = @UniqueConstraint(columnNames = { "EmployName" }))
public class Employ implements java.io.Serializable, Comparable<Employ> {

    private Integer employNumber;
    private String employName;
    private String password;
    private boolean superManager;
    private Set<Timesheet> timesheets = new HashSet<Timesheet>(0);

    public Employ() {
    }

    public Employ(String employName, String password, boolean superManager) {
        this.employName = employName;
        this.password = password;
        this.superManager = superManager;
    }

    public Employ(String employName, String password, boolean superManager,
            Set<Timesheet> timesheets) {
        this.employName = employName;
        this.password = password;
        this.superManager = superManager;
        this.timesheets = timesheets;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EmployNumber", unique = true, nullable = false)
    public Integer getEmployNumber() {
        return this.employNumber;
    }

    public void setEmployNumber(Integer employNumber) {
        this.employNumber = employNumber;
    }

    @Column(name = "EmployName", nullable = false, length = 45)
    public String getEmployName() {
        return this.employName;
    }

    public void setEmployName(String employName) {
        this.employName = employName;
    }

    @Column(name = "Password", nullable = false, length = 45)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "SuperManager", columnDefinition = "BIT", length = 1, nullable = false)
    public boolean isSuperManager() {
        return this.superManager;
    }

    public void setSuperManager(boolean superManager) {
        this.superManager = superManager;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employ")
    public Set<Timesheet> getTimesheets() {
        return this.timesheets;
    }

    public void setTimesheets(Set<Timesheet> timesheets) {
        this.timesheets = timesheets;
    }

    @Override
    public int compareTo(Employ o) {
        return this.getEmployName().compareTo(o.getEmployName());
    }

}
