package cst.timesheet_JPA.model;

// Generated 12-Nov-2013 6:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name = "RECORD", catalog = "Timesheet", uniqueConstraints = @UniqueConstraint(columnNames = {
        "TimesheetId", "Project", "WP" }))
public class Record implements java.io.Serializable {

    private Integer recordId;
    private Timesheet timesheet;
    private int project;
    private String wp;
    private BigDecimal sat;
    private BigDecimal sun;
    private BigDecimal mon;
    private BigDecimal tue;
    private BigDecimal wed;
    private BigDecimal thu;
    private BigDecimal fri;
    private String note;

    public Record() {
    }

    public Record(Timesheet timesheet, int project, String wp) {
        this.timesheet = timesheet;
        this.project = project;
        this.wp = wp;
    }

    public Record(Timesheet timesheet, int project, String wp, BigDecimal sat,
            BigDecimal sun, BigDecimal mon, BigDecimal tue, BigDecimal wed,
            BigDecimal thu, BigDecimal fri, String note) {
        this.timesheet = timesheet;
        this.project = project;
        this.wp = wp;
        this.sat = sat;
        this.sun = sun;
        this.mon = mon;
        this.tue = tue;
        this.wed = wed;
        this.thu = thu;
        this.fri = fri;
        this.note = note;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "RecordId", unique = true, nullable = false)
    public Integer getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TimesheetId", nullable = false)
    public Timesheet getTimesheet() {
        return this.timesheet;
    }

    public void setTimesheet(Timesheet timesheet) {
        this.timesheet = timesheet;
    }

    @Column(name = "Project", nullable = false)
    public int getProject() {
        return this.project;
    }

    public void setProject(int project) {
        this.project = project;
    }

    @Column(name = "WP", nullable = false, length = 45)
    public String getWp() {
        return this.wp;
    }

    public void setWp(String wp) {
        this.wp = wp;
    }

    @Column(name = "Sat", precision = 3, scale = 1)
    public BigDecimal getSat() {
        return this.sat;
    }

    public void setSat(BigDecimal sat) {
        this.sat = sat;
    }

    @Column(name = "Sun", precision = 3, scale = 1)
    public BigDecimal getSun() {
        return this.sun;
    }

    public void setSun(BigDecimal sun) {
        this.sun = sun;
    }

    @Column(name = "Mon", precision = 3, scale = 1)
    public BigDecimal getMon() {
        return this.mon;
    }

    public void setMon(BigDecimal mon) {
        this.mon = mon;
    }

    @Column(name = "Tue", precision = 3, scale = 1)
    public BigDecimal getTue() {
        return this.tue;
    }

    public void setTue(BigDecimal tue) {
        this.tue = tue;
    }

    @Column(name = "Wed", precision = 3, scale = 1)
    public BigDecimal getWed() {
        return this.wed;
    }

    public void setWed(BigDecimal wed) {
        this.wed = wed;
    }

    @Column(name = "Thu", precision = 3, scale = 1)
    public BigDecimal getThu() {
        return this.thu;
    }

    public void setThu(BigDecimal thu) {
        this.thu = thu;
    }

    @Column(name = "Fri", precision = 3, scale = 1)
    public BigDecimal getFri() {
        return this.fri;
    }

    public void setFri(BigDecimal fri) {
        this.fri = fri;
    }

    @Column(name = "Note")
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
