package cst.timesheet_JPA.model;

// Generated 12-Nov-2013 6:05:43 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Timesheet generated by hbm2java
 */
@Entity
@Table(name = "TIMESHEET", catalog = "Timesheet", uniqueConstraints = @UniqueConstraint(columnNames = {
        "EmployNumber", "WeekEnd" }))
public class Timesheet implements java.io.Serializable {

    private Integer timesheetId;
    private Employ employ;
    private Date weekEnd;
    @SuppressWarnings("rawtypes")
    private Set records = new HashSet(0);

    public Timesheet() {
    }

    public Timesheet(Employ employ, Date weekEnd) {
        this.employ = employ;
        this.weekEnd = weekEnd;
    }

    @SuppressWarnings("rawtypes")
    public Timesheet(Employ employ, Date weekEnd, Set records) {
        this.employ = employ;
        this.weekEnd = weekEnd;
        this.records = records;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TimesheetId", unique = true, nullable = false)
    public Integer getTimesheetId() {
        return this.timesheetId;
    }

    public void setTimesheetId(Integer timesheetId) {
        this.timesheetId = timesheetId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "EmployNumber", nullable = false)
    public Employ getEmploy() {
        return this.employ;
    }

    public void setEmploy(Employ employ) {
        this.employ = employ;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WeekEnd", nullable = false, length = 19)
    public Date getWeekEnd() {
        return this.weekEnd;
    }

    public void setWeekEnd(Date weekEnd) {
        this.weekEnd = weekEnd;
    }

    @SuppressWarnings("rawtypes")
    @OneToMany(targetEntity = Record.class, fetch = FetchType.LAZY, mappedBy = "timesheet")
    public Set getRecords() {
        return this.records;
    }

    @SuppressWarnings("rawtypes")
    public void setRecords(Set records) {
        this.records = records;
    }

}
