package cst.is.asn3.quiz.model;
// Generated 3-Dec-2013 8:32:49 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name="Quiz")
public class Quiz  implements java.io.Serializable {


     private Integer idQuiz;
     private int week;
     private Set<QuizTaken> quizTakens = new HashSet<QuizTaken>(0);
     private Set<Question> questions = new HashSet<Question>(0);

    public Quiz() {
    }

	
    public Quiz(int week) {
        this.week = week;
    }
    public Quiz(int week, Set<QuizTaken> quizTakens, Set<Question> questions) {
       this.week = week;
       this.quizTakens = quizTakens;
       this.questions = questions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idQuiz", unique=true, nullable=false)
    public Integer getIdQuiz() {
        return this.idQuiz;
    }
    
    public void setIdQuiz(Integer idQuiz) {
        this.idQuiz = idQuiz;
    }

    
    @Column(name="week", nullable=false)
    public int getWeek() {
        return this.week;
    }
    
    public void setWeek(int week) {
        this.week = week;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="quiz")
    public Set<QuizTaken> getQuizTakens() {
        return this.quizTakens;
    }
    
    public void setQuizTakens(Set<QuizTaken> quizTakens) {
        this.quizTakens = quizTakens;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="quiz")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }




}


