package cst.is.asn3.quiz.model;
// Generated 3-Dec-2013 8:32:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuizTaken generated by hbm2java
 */
@Entity
@Table(name="QuizTaken")
public class QuizTaken  implements java.io.Serializable {


     private QuizTakenId id;
     private User user;
     private Quiz quiz;
     private int score;

    public QuizTaken() {
    }

    public QuizTaken(QuizTakenId id, User user, Quiz quiz, int score) {
       this.id = id;
       this.user = user;
       this.quiz = quiz;
       this.score = score;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUser", column=@Column(name="idUser", nullable=false) ), 
        @AttributeOverride(name="idQuiz", column=@Column(name="idQuiz", nullable=false) ) } )
    public QuizTakenId getId() {
        return this.id;
    }
    
    public void setId(QuizTakenId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idQuiz", nullable=false, insertable=false, updatable=false)
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }

    
    @Column(name="score", nullable=false)
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }




}


