package cst.is.asn3.quiz.model;
// Generated 3-Dec-2013 8:32:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuizTakenId generated by hbm2java
 */
@Embeddable
public class QuizTakenId  implements java.io.Serializable {


     private int idUser;
     private int idQuiz;

    public QuizTakenId() {
    }

    public QuizTakenId(int idUser, int idQuiz) {
       this.idUser = idUser;
       this.idQuiz = idQuiz;
    }
   


    @Column(name="idUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="idQuiz", nullable=false)
    public int getIdQuiz() {
        return this.idQuiz;
    }
    
    public void setIdQuiz(int idQuiz) {
        this.idQuiz = idQuiz;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuizTakenId) ) return false;
		 QuizTakenId castOther = ( QuizTakenId ) other; 
         
		 return (this.getIdUser()==castOther.getIdUser())
 && (this.getIdQuiz()==castOther.getIdQuiz());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUser();
         result = 37 * result + this.getIdQuiz();
         return result;
   }   


}


